### PR TITLE
Updated GetAllOrganisations to not filter on Status

### PR DESCRIPTION
**Pull request by davidgouge**

### CODE REVIEW

**Comment by jcoxhead** [comment]
Hi Dave - I am guessing you want to retrieve all records for organisation irregardless of whether they are deleted as the client will determine what to display. Should we do this also for all other queries like contacts?

Also what do we do for say get contact by username? if one is deleted and another one as been added as at the moment that is designed to returns only one record?

**Comment by davidgouge** [comment]
Worry about the others when we get to them.

**Comment by jcoxhead** [comment]
ok but Lets talk at the review - we should be able to work this out. 
We don't want to mix concepts. It will become a mess.

**Comment by jcoxhead** [comment]
I will approve it for now.

**Pull request merged**
